services:
    db:
        image: marvstunt/wordsmith:db
        container_name: db
    
    web:
        image: marvstunt/wordsmith:web
        ports:
          - "8080:80"
        container_name: web
        depends_on:
          - words
        volumes:
          - ./web/static:/app/static

    words:
        image: marvstunt/wordsmith:words
        container_name: words
        depends_on:
          - db